<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.classmatechen</groupId>
        <artifactId>ad-request-util</artifactId>
        <version>Libra</version>
    </parent>

    <artifactId>oceanengine</artifactId>
    <version>Libra</version>
    <packaging>jar</packaging>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.16</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.classmatechen</groupId>
            <artifactId>basic</artifactId>
            <version>Libra</version>
        </dependency>
        <!-- 巨量引擎开放平台 -->
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>oceanengine-mapi-java-client</artifactId>
            <version>1.1.42</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>OceanengineOpenApi</id>
            <name>ad_open_sdk_java</name>
            <layout>default</layout>
            <url>https://artifact.bytedance.com/repository/releases/</url>
        </repository>
    </repositories>
</project>